const money = 300
const hp = 100
const gold = 0
const online = false

const heroes = [
    {
        username: "alexstrasza",
        image: "http://localhost:8000/heroes/alexstrasza.jpg",
        money,
        gold,
        hp,
        online,
        battleWeapon: {},
        battleArmour: {},
        battlePotion: {},
    },
    {
        username: "draka",
        image: "http://localhost:8000/heroes/draka.jpg",
        money,
        gold,
        hp,
        online,
        battleWeapon: {},
        battleArmour: {},
        battlePotion: {},
    },
    {
        username: "yrel",
        image: "http://localhost:8000/heroes/yrel.jpg",
        money,
        gold,
        hp,
        online,
        battleWeapon: {},
        battleArmour: {},
        battlePotion: {},
    },
    {
        username: "jaina",
        image: "http://localhost:8000/heroes/jaina.jpg",
        money,
        gold,
        hp,
        online,
        battleWeapon: {},
        battleArmour: {},
        battlePotion: {},
    },
    {
        username: "khadgar",
        image: "http://localhost:8000/heroes/khadgar.jpg",
        money,
        gold,
        hp,
        online,
        battleWeapon: {},
        battleArmour: {},
        battlePotion: {},
    },
    {
        username: "ladyliadrin",
        image: "http://localhost:8000/heroes/ladyliadrin.jpg",
        money,
        gold,
        hp,
        online,
        battleWeapon: {},
        battleArmour: {},
        battlePotion: {},
    },
    {
        username: "rexxar",
        image: "http://localhost:8000/heroes/rexxar.jpg",
        money,
        gold,
        hp,
        online,
        battleWeapon: {},
        battleArmour: {},
        battlePotion: {},
    },
    {
        username: "thrall",
        image: "http://localhost:8000/heroes/thrall.jpg",
        money,
        gold,
        hp,
        online,
        battleWeapon: {},
        battleArmour: {},
        battlePotion: {},
    },
    {
        username: "tyrande",
        image: "http://localhost:8000/heroes/tyrande.jpg",
        money,
        gold,
        hp,
        online,
        battleWeapon: {},
        battleArmour: {},
        battlePotion: {},
    },
    {
        username: "turalyon",
        image: "http://localhost:8000/heroes/turalyon.jpg",
        money,
        gold,
        hp,
        online,
        battleWeapon: {},
        battleArmour: {},
        battlePotion: {},
    },
    {
        username: "uther",
        image: "http://localhost:8000/heroes/uther.jpg",
        money,
        gold,
        hp,
        online,
        battleWeapon: {},
        battleArmour: {},
        battlePotion: {},
    },
    {
        username: "voljin",
        image: "http://localhost:8000/heroes/voljin.jpg",
        money,
        gold,
        hp,
        online,
        battleWeapon: {},
        battleArmour: {},
        battlePotion: {},
    },
]

module.exports = {
    heroes
}